{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sample.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "sample.name" . }}
    chart: {{ template "sample.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}




{{- toYaml $ | include "null" -}}
### variable($x) vs root($.x)
{{- define "null" }}{{ end }}
$fullName  >> {{ "<undefined>" }}{{/* $fullName  | default "<null>" */}}
$.fullName >> {{ $.fullName | default "<null>" }}

### handle root dict
{{- $container := "aaa" }}
{{- set $ "container" "bbb" | include "null" }}
$container  >> {{ $container }}
$.container >> {{ $.container }}

### handle template as dict
{{- define "ingress" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "sample.fullname" . }}
  labels:
    app: {{ template "sample.name" . }}
    chart: {{ template "sample.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
{{- define "expend" -}}
labels:
  new: "append"
  chart: "replace"
{{- end }}

{{- include "ingress" $ | fromYaml | set $ "ingress" | include "null" }}
{{- include "expend"  $ | fromYaml | set $ "expend"  | include "null" }}
$.ingress >>
{{ toYaml $.ingress | indent 2 }}
$.expend >>
{{ toYaml $.expend  | indent 4 }}
$.ingress + $.expend >>
{{- merge $.ingress.metadata $.expend | include "null" }}
{{ toYaml $.ingress | indent 2 }}


### helm template sample
expend:
  - path: ingress@metadata.labels
    #labels:
      new: "append"
      chart: "replace"
  - path: deployment@spec.template.spec.containers[0]
    #containers:
      name: hygieia-web
      image: "hygieia-web:stable"
      imagePullPolicy: Always
